version: '3.8'

services:
  frontend:
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://robin:Robin123@mysql/db
      - RAG_MODEL_URL=http://vllm:8000
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ichat
      MYSQL_USER: robin
      MYSQL_PASSWORD: Robin123
    volumes:
      - mysql_data:/var/lib/mysql

  vllm:
    build:
      context: ./docker
      dockerfile: vllm.Dockerfile
    ports:
      - "8000:8000"

volumes:
  mysql_data: